### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by johancvb** [RowinRuizendaal/web-app-from-scratch-2021#1]
App ziet er goed uit, erg strak.
Code is ook netjes, en werkend. Niets aan toe te voegen.

#Repository
Er is geen repo-description, en de repo bevat ook geen readme. De API is dus ook niet uitgelegd in de readme.

#Code
De code is strak, consistent, en op volgorde. 
Duidelijke id/class variabelen. Code flow is goed te lezen.

Carousel mis ik wel, maar dat komt door een mislukte push, maar de code ziet er goed uit

**Comment by RowinRuizendaal** [comment]
Thanks voor je feedback, ik heb deze punten verwerkt :)
