### ISSUE TITLE
Readme.md API

### ISSUE THREAD

**Issue by Mokerstier** [RowinRuizendaal/web-app-from-scratch-2021#10]
Mis nog wat info over je API

- aantal requests?

**Comment by RowinRuizendaal** [comment]
Hoi, ik kan helaas niks vinden over het aantal toegestaan request, wat ik het slimste om dan hier neer te zetten?

**Comment by RowinRuizendaal** [comment]
Hey,

bedankt voor de informatie op discord, ik heb hem nu alvast in mijn README gezet (local) ;)
