### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by Mokerstier** [RowinRuizendaal/web-app-from-scratch-2021#13]
https://github.com/RowinRuizendaal/web-app-from-scratch-2021/blob/07bd010de3d29e2a3f85c436df0d1a1e7cf9ecb6/js/modules/carousel/fillCarousel.js#L36

kan dit weg?

**Comment by RowinRuizendaal** [comment]
Hey, bedankt voor je feedback, deze was ik inderdaad vergeten weg te halen :)
