### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Mokerstier** [RowinRuizendaal/web-app-from-scratch-2021#2]
https://github.com/RowinRuizendaal/web-app-from-scratch-2021/blob/bb6122c5483f9aab51e5c499b57b710318ca4e09/js/app.js#L24

Dit klopt niet helemaal een mooiere oplossing zou zijn:
```
const results = document.querySelector('.results h3');
results .textContent = `${data.length} results for ${artist}`;
```

Voordeel hieraan is dat je results nu weer opnieuw zou kunnen wijzigen door `results.textContent = "jouw waarde"`
In jouw geval zou je een nieuwe variabele moeten aanmaken en eerst weer een querySelector moeten doen.

**Comment by RowinRuizendaal** [comment]
Bedankt voor je feedback!
