### ISSUE TITLE
Peer review web app from scratch 20/21 #week 1

### ISSUE THREAD

**Issue by ofahchouch-gh** [RowinRuizendaal/web-app-from-scratch-2021#3]
# De code bevat geen syntaxfouten en is netjes opgemaakt
De structuur is duidelijk en logisch opgezet. Misschien wel nu al met modules werken though? Of was je dat vanaf week 2 van plan?

Bij het maken van functies en variabelen wil je de intentie (intent) waarvoor je de variabel/functie gaat gebruiken weergeven en niet zo zeer wat er precies gebeurd in de variabel/functie. Is het niet verstandiger om voor functienamen de intentie te beschrijven in plaats van de naam van de entiteit?

Verder wil je ook met abstractielagen werken in methods. Elke method bestaat uit maar 1 abstractielaag. Ook dat doe je goed.

# JSON data kan met een asynchrone request worden opgehaald uit een API
Het is je gelukt om data asynchroon met async/await op te halen uit de API.

# JSON data kan, al dan niet met een micro library, client side in de HTML worden gerenderd.
Het is je gelukt om gebruik te maken van het renderen van client side code in de HTML zoals we zien bij de arrow function carousel. 

Je carousel ziet er heel mooi uit. Het is ook mobile responsive. Heel goed dat je daar nu al over nadenkt!

Verder zie ik niet dat je jezelf aan het herhalen bent in je code (DRY principe) en je maakt gebruik van scopes.

# Over de Readme
De readme moet nog geupdate worden zie ik. Maar dat wist je zelf ook al :)!

**Comment by RowinRuizendaal** [comment]
Thanks voor je feedback, ik heb deze punten verwerkt :)
