### ISSUE TITLE
Repository peer feedback week 2

### ISSUE THREAD

**Issue by HappyPantss** [RowinRuizendaal/web-app-from-scratch-2021#4]
Repository
Hey Rowin, bij deze mijn peer review op jouw repository voor de WAFS API opdracht, week 2.

Zie de vinkjes (✔️) en kruisjes (❌) niet als fout of goed, maar een vinkje is voor als je heta af hebt, en een kruisje voor als er nog iets mist :).

✔️ Is there a link to the live demo at the top?
Jazeker! Alleen nog een tip voor je 'description': ik zou hier nog even in het kort  uitleggen wat/ waar voor het project is. En misschien wat tags toevoegen is altijd leuk :).

✔️ Is the concept described well in the readme?
Je hebt bij je description geschreven dat je doormiddel van de API, de huidige nummers van de artist kan ophalen, wat goed is! Ik zou alleen nog even beschrijven wat je app allemaal kan.

✔️ Is the API described in the readme?
Ja! Goede beschrijven wat de API is en hoe je data fetched. 

✔️ Are the Actor and Interaction diagrams included?
Ja!

Keep coding~~

**Comment by RowinRuizendaal** [comment]
Bedankt voor je feedback, ik heb even wat tags toegevoegd ;)
