### ISSUE TITLE
Peer review week 2

### ISSUE THREAD

**Issue by johancvb** [RowinRuizendaal/web-app-from-scratch-2021#5]
### **Repository**
Scan your buddy's repository
Is there a link to the live demo at the top?
- Die is er wel, maar hij werkt niet correct :)

Is the concept described well in the readme?
- Het concept wordt niet heel uitgebreid uitgelegd, maar wordt wel met gebruik van screenshots van de app duidelijker gemaakt.

Is the API described in the readme?
- Ja, de API wordt uitgelegd, en ook wordt de code gedeeld over het fetchen vanuit de API. Bovendien staat er ook een link naar de API-site.

Are the Actor and Interaction diagrams included?
- Ja!

### **Code**
**Actor Diagram**
Using the Actor diagram, figure out the structure of the code
Do the actors make sense to you?
- De actors wel, maar er zit geen flow tussen de actors. Hierdoor kan ik dus niet duidelijk zien welke actors er met elkaar "communiceren".

Do you see any function you wouldn't expect for a certain Actor?
- Nee, het spreekt allemaal voor zich :)

**Interaction Diagram**
Using the interaction diagram, figure out how the app functions
Does the flow make sense to you?
- Ja, duidelijk en overzichtelijk uitgelegd.

Does anything work differently than you would code it?
- Ik zou misschien de flows tussen de elementen aanpassen, zodat er duidelijk te zien is welke elementen er worden aangeroepen in het interaction diagram.

**Click through the live demo**
Does it work the way you would expect it to?
- Ja!! Ziet er super vet uit, en werkt ook helemaal prima. Alleen is soms de afbeelding van een nummer/album niet beschikbaar, maar dit komt door de API.

What features or improvements would you like to see?
- Misschien een filter mogelijkheid, of zoekbalk? Hierdoor kun je specifiek zoeken naar een bepaald nummer/genre.

**BROWSE the code**
Has it already been structured according to the diagrams?
- Ja.

Check the code for consistency, is code being written the same way in different places?
- Zeker, de code is consistent geschreven, met een duidelijke structuur, wat zorgt voor een overzichtelijk script.

Does the code follow naming conventions? Do variable and function names make sense to you?
- Er worden goeie variabelnamen gebruikt, erg compact en duidelijk. Way to goooo.

Yoo! Je app ziet er goed uit man. Super nice om te zien, en om te gebruiken.
Blijf zo doorgaan!!

--Johan

**Comment by RowinRuizendaal** [comment]
Hoi Johan,

bedankt voor je feedback :), ik heb het zojuist verwerkt
