### ISSUE TITLE
Code peer feedback week 2

### ISSUE THREAD

**Issue by HappyPantss** [RowinRuizendaal/web-app-from-scratch-2021#7]
Code
Hey Rowin, bij deze mijn peer review op jouw code voor de WAFS API opdracht, week 2.

Zie de vinkjes (✔️) en kruisjes (❌) niet als fout of goed, maar een vinkje is voor als je heta af hebt, en een kruisje voor als er nog iets mist :).

## Using the Actor diagram, figure out the structure of the code
✔️ Do the actors make sense to you?
Ja zeker, alle belangrijke actors worden mee genomen (voor zover ik weet).

✔️ Do you see any function you wouldn't expect for a certain Actor?
Is zie geen rare functies!

## Using the interaction diagram, figure out how the app functions
✔️❌ Does the flow make sense to you?
Misschien kan je de 'On page load' en 'On first time vist' iets breeder uit elkaar zetten, ik weet nu niet zo goed waar ik moet beginnen. Voor de rest is de flow erg goed te volgen, ook goed dat je opties van wat er gebeurd als iets wel en niet lukt!

## Click through the live demo
✔️❌ Does it work the way you would expect it to? / What features or improvements would you like to see?
- Ik vind het duidelijk dat er onder aan de pagina de artiesten staan, maar misschien kan je hier nog een kopje zetten met 'Artist'. Dit maakt het makkelijk voor de gebruiker om te zien wat het nou eigenlijk is.
- Zodra ik op een artist heb gedrukt, zie ik een duidelijke carousell, ik snap dat ik er doorheen kan slepen en de nummers kan afspelen! Alleen zie ik geen knopje om terug te gaan, en terug gaan met mn muis werkt ook niet.. alleen refresh natuurlijk. Misschien kan je hier nog naar kijken.

Ideetjes:
Geen idee of het kan, maar het lijkt mij wel vet om de meest geluisterde nummers op de hoofdpagina te zien.

## Browse  the code
✔️❌ Has it already been structured according to the diagrams?
De namen komen niet perse overeen, maar je hebt wel alle elementen.

✔️ Think of structural improvements
Goed gedaan! Hier weet ik geen feedback voor.

✔️Check the code against our best practices
Je gebruikt innerHTML, wat goed is, maar bedenk goed of dit de goede oplossing is voor jezelf! (ik vind van wel, maar let hier wel op :))

✔️Check the code for consistency, is code being written the same way in different places?
Jep it does! Goed op gelet.

✔️ Does the code follow naming conventions? Do variable and function names make sense to you?
De enige naam die mij verward, is secondcontainer2 haha.. Is dit de 2de container van de 2de container? Voor de rest goed gedaan.

Keep coding~~

**Comment by RowinRuizendaal** [comment]
Bedankt voor je feedback, ik heb hier wat aan gehad ;)
